### ISSUE TITLE
Why is this warning there and how to address it?

### ISSUE THREAD

**Issue by andrekolodochka** [andrekolodochka/action-tutorial#2]
`Unexpected input(s) 'token', valid inputs are ['']`
https://github.com/andrekolodochka/action-tutorial/actions/runs/3067282527

**Comment by affrae** [comment]
So it is just a warning - not an error. It says that you have not defined the inputs to your actions in the action.yml file?



```
name: "my joke action"

description: "use an external API to retrieve and display a joke"

outputs:
  joke-output:
    description: The resulting joke from the icanhazdadjokes API

runs:
  using: "node12"
  main: "main.js"
```

This is your action.yml file - you need to define the inputs. It won't break you action it will just nag you. See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs for an example
